# Generated by Django 5.0.6 on 2024-06-05 14:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0005_idrecord_title_alter_idrecord_id_value"),
    ]

    operations = [
        migrations.AlterField(
            model_name="idrecord",
            name="id_value",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
